name: Pavlos Test Workflow

on:
  pull_request: # Triggered on pull request events
    types: [ opened, synchronize ]

#  SKIP_REGRESSION: "${{ contains(github.event.pull_request.labels.*.name, 'ci-condition: skip-regression') }}"
env:
  SKIP_REGRESSION: 'true'


jobs:
  check-skip-regression:
    runs-on: ubuntu-latest
    outputs:
      skip: ${{ steps.set-skip.outputs.SKIP_REGRESSION }}
    steps:
      - name: Set SKIP_REGRESSION based on a label
        id: set-skip
        run: |
          if [[ "${{ contains(github.event.pull_request.labels.*.name, 'ci-condition: skip-regression') }}" == "true" ]]; then
            echo "SKIP_REGRESSION=true" >> $GITHUB_OUTPUT
          else
            echo "SKIP_REGRESSION=false" >> $GITHUB_OUTPUT
          fi

  job1:
    runs-on: ubuntu-latest
    if: needs.check-skip-regression.outputs.skip == 'false'
    steps:
      - name: Print message for Job 1
        run: echo "hi job 1"

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Print message for Job 2
        run: echo "hi job 2"

  job3:
    runs-on: ubuntu-latest
    needs:
      - check-skip-regression
      - job1
      - job2
    if: needs.check-skip-regression.outputs.skip == 'false'
    steps:
      - name: Print message for Job 3
        run: echo "hi job 3, depends on both job1 and job2"
