name: Pavlos Test Workflow

on:
  pull_request: # Triggered on pull request events
    types: [ opened, synchronize ]

#  SKIP_REGRESSION: "${{ contains(github.event.pull_request.labels.*.name, 'ci-condition: skip-regression') }}"
env:
  SKIP_REGRESSION: 'true'


jobs:
  check-should-run:
    runs-on: ubuntu-latest
    outputs:
      should-run: ${{ steps.set-should-run.outputs.SHOULD_RUN }}
    steps:
      - name: Determine if
        id: set-should-run
        run: |
          if [[ "${{ contains(github.event.pull_request.labels.*.name, 'ci-condition: skip-regression') }}" == "true" ]]; then
             if [[ "${{ github.event_name == 'pull_request_review' }}" == "true" ]]; then
                echo "SHOULD_RUN=true" >> ${GITHUB_OUTPUT}
             else
                echo "SHOULD_RUN=false" >> ${GITHUB_OUTPUT}
          else
             echo "SHOULD_RUN=true" >> ${GITHUB_OUTPUT}
          fi

  job1:
    runs-on: ubuntu-latest
    needs: check-should-run
    if: needs.check-should-run.outputs.should-run == 'false'
    steps:
      - name: Print message for Job 1
        run: echo "hi job 1"

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Print message for Job 2
        run: echo "hi job 2"

  job3:
    runs-on: ubuntu-latest
    needs:
      - check-should-run
      - job1
      - job2
    if: needs.check-should-run.outputs.skip == 'false'
    steps:
      - name: Print message for Job 3
        run: echo "hi job 3, depends on both job1 and job2"
